version: "3.8"

networks:
  base-network:
    driver: bridge
    name: ipfs-cube-network
  # ipfs-network:
  #   driver: bridge
  #   name: ipfs-network

volumes:
  ctx:
    driver: local
    driver_opts:
      type: none
      device: ../../
      # device: $PWD/${WEB_APP_PATH}
      o: bind

services:

  app:
    image: ipfs-cube.app
    build:
      context: ./app
      dockerfile: ./dev.Dockerfile
      args:
        workdir:  /ctx/ipfs-cube/bin/app
    command: tail -f /dev/null
    # command: bash f dev
    ports:
      - 7788:7788
      - 3080:8080
      # - 8085:8080
    networks:
      - base-network
    # user: 1000:1000
    volumes:
      - ./app/.user:/root
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 13000M

  compiler:
    image: ipfs-cube.compiler
    build:
      context: ./compiler
      dockerfile: ./Dockerfile
      args:
        workdir: /ctx/ipfs-cube/bin/compiler
    command: tail -f /dev/null
    # command: bash f dev
    # expose:
    #   - 7788
    ports:
      - 3000:3000
      - 3001:3001
      - 9500:9500
      - 8899:8899
      - 9630:9630
    environment:
      - BAR_PORT=7001
      - SHADOWCLJS_DEVTOOLS_URL=http://localhost:9630
    networks:
      - base-network
    # user: 1000:1000
    volumes:
      - ./compiler/.user:/root
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
