version: "3.8"

networks:
  dev-network:
    driver: overlay
    name: find-dev
  main-network:
    driver: overlay
    name: find-peer${FIND_PEER_INDEX}
  ipfs-network:
    driver: bridge
    name: find-ipfs

volumes:
  ctx:
    driver: local
    driver_opts:
      type: none
      device: ../../
      o: bind
  dgraph-volume:
    name: find-dgraph-peer${FIND_PEER_INDEX}
  ipfs-volume:
    name: find-ipfs-peer${FIND_PEER_INDEX}

services:

  app:
    image: find.app
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        workdir:  /ctx/find/bin/app
    command: tail -f /dev/null
    # command: bash f dev
    ports:
      - ${FIND_REPL_PORT}:7781
      - ${FIND_HTTP_PORT}:4080
    environment:
      - FIND_SYSTEM_TRAY=false
    networks:
      main-network:
    volumes:
      - ./app/volumes/root${FIND_PEER_INDEX}:/root
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  zero:
    image: dgraph/dgraph:v20.11.2
    volumes:
      - dgraph-volume:/dgraph
    networks:
      main-network:
    # ports:
    #   - 5080:5080
    #   - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  
  alpha:
    image: dgraph/dgraph:v20.11.2
    volumes:
      - dgraph-volume:/dgraph
    networks:
      main-network:
    # ports:
    #   - 8080:8080
    #   - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --whitelist "0.0.0.0/0"
  
  ratel:
    image: dgraph/dgraph:v20.11.2
    networks:
      main-network:
    ports:
      - 804${FIND_PEER_INDEX}:8000
    command: dgraph-ratel

  ipfs:
    image: find.ipfs
    build:
      context: ./ipfs
      dockerfile: ./Dockerfile
    ports:
      - 440${FIND_PEER_INDEX}:4001
      - 540${FIND_PEER_INDEX}:5001
      - 840${FIND_PEER_INDEX}:8080
      - 848${FIND_PEER_INDEX}:8081
      # - 4001:4001
    #   - 127.0.0.1:5001:5001
    #   # - 127.0.0.1:8080:8080
    #   # - 127.0.0.1:8081:8081
    environment:
      # - FOO=bar
      # - IPFS_PROFILE=server
      # - IPFS_PROFILE=local-discovery
      # - IPFS_PATH=/data/ipfs
      - IPFS_PATH=/data/ipfs
    networks:
      main-network:
      ipfs-network:
        aliases:
          - ipfs${FIND_PEER_INDEX}
    volumes:
      - ./ipfs/volumes/ipfs${FIND_PEER_INDEX}:/data/ipfs
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
      # - type: volume
      #   source: ipfs-volume
      #   target: /data/ipfs
      #   volume:
      #     nocopy: true

  ipfs-link:
    image: find.ipfs-link
    build:
      context: ./ipfs-link
      dockerfile: ./Dockerfile
      args:
        workdir:  /ctx/find/bin/ipfs-link
    command: tail -f /dev/null
    ports:
      - 844${FIND_PEER_INDEX}:8000
    environment:
      - FOO=bar
    networks:
      main-network:
      dev-network:
      # ipfs-network:
      #   aliases:
      #     - ipfs${FIND_PEER_INDEX}
    volumes:
      - ./ipfs-link/volumes/root${FIND_PEER_INDEX}:/root
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M