version: "3.8"

networks:
  dev-network:
    driver: overlay
    name: find-dev
  main-network:
    driver: overlay
    name: find-peer${FIND_PEER_INDEX}
  ipfs-network:
    driver: bridge
    name: find-ipfs

volumes:
  ctx:
    driver: local
    driver_opts:
      type: none
      device: ../../
      o: bind
  ipfs-volume:
    name: find-ipfs-peer${FIND_PEER_INDEX}

services:

  app:
    image: find.app
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        workdir:  /ctx/find/bin/app
    command: tail -f /dev/null
    # command: bash f dev
    ports:
      - ${FIND_REPL_PORT}:7781
      - ${FIND_HTTP_PORT}:4080
    environment:
      - FIND_SYSTEM_TRAY=false
    networks:
      main-network:
    volumes:
      - ./app/volumes/root${FIND_PEER_INDEX}:/root
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M

  ipfs:
    image: find.ipfs
    build:
      context: ./ipfs
      dockerfile: ./Dockerfile
    ports:
      - 440${FIND_PEER_INDEX}:4001
      - 540${FIND_PEER_INDEX}:5001
      - 840${FIND_PEER_INDEX}:8080
      - 848${FIND_PEER_INDEX}:8081
      # - 4001:4001
    #   - 127.0.0.1:5001:5001
    #   # - 127.0.0.1:8080:8080
    #   # - 127.0.0.1:8081:8081
    environment:
      # - FOO=bar
      # - IPFS_PROFILE=server
      # - IPFS_PROFILE=local-discovery
      # - IPFS_PATH=/data/ipfs
      - IPFS_PATH=/data/ipfs
    networks:
      main-network:
      ipfs-network:
        aliases:
          - ipfs${FIND_PEER_INDEX}
    volumes:
      - ./ipfs/volumes/ipfs${FIND_PEER_INDEX}:/data/ipfs
      - type: volume
        source: ctx
        target: /ctx
        volume:
          nocopy: true
      # - type: volume
      #   source: ipfs-volume
      #   target: /data/ipfs
      #   volume:
      #     nocopy: true